#my aliases
alias c='clear'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -i'
alias ls='ls -h --color'
alias h='history | grep $1'
alias reload='source ~/.bashrc'
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias sessions='tmux list-sessions'
alias switch='tmux switch -t $1'
alias prettyjson='cat $1 | python -mjson.tool'
